FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements-fastapi.txt /app/requirements-fastapi.txt

RUN pip3 install -r requirements-fastapi.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "app:app"]