Transform: 'AWS::Serverless-2016-10-31'

Description: >
    FastAPI with aws sam

Resources:
  FastapiLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["app.lambda_handler"]
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: v1