AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: >
    FastAPI with aws sam

Resources:
  FastapiLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["app.handler"]
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: v1