name: Build and package fastapi app to github registry
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_REGISTRY }}

      - name: build fastapi app and push to registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: ghcr.io/dudeperf3ct/fastapi-distilbert:latest
          push: true
